### PR TITLE
cache: refactor, and fix of race condition between expiration goroutine and external calls.

### PR DESCRIPTION
**Pull request by colindickson**
Solves https://github.com/ethpandaops/checkpointz/issues/117

### CODE REVIEW

**Comment by colindickson** [comment]
Notes:

Created private "lock-free" versions of the Add/Delete/Get/Len methods to be called internally.  This way, the goroutine that is running which deletes expired items can acquire a write-lock on the map and do all of its work using these methods without worrying about a concurrent operation on the map.

**Comment by samcm** [comment]
Thanks @colindickson!!

**Comment by samcm** [comment]
Any chance you could look at the linting errors @colindickson? I'll merge + release once we're good to go :)

**Review by samcm — APPROVED** [review]

**Comment by samcm** [comment]
Included in https://github.com/ethpandaops/checkpointz/releases/tag/v0.18.0! Thanks again @colindickson 🎉

**Pull request merged**
